### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by stilcrad** [lisiqi19971013/SuperFast#1]
This is a great job!!! I want to know if this training code will be made public?

**Comment by stilcrad** [comment]
In the demo of the video reconstruction, the ground truth of the high-speed camera had to be used, which was confusing. How can we use the model without high-speed camera data？For example, I only have the images of low-speed cameras and the data of event cameras, and the timestamps of each frame.

**Comment by lisiqi19971013** [comment]
1) Thank you for your interest. We are continuing to work on the task, and the training code will be released when after the new work is done. The detailed training process are provided in our paper.
2) As mentioned in our paper, we use the GT video skipped 199 frames as input for **quantitative VFI evaluation**. This is due to the fact that the brightness intensity of GT video frames is different from that of DAVIS video frames (DAVIS video frames are darker). If we use the low-speed DAVIS video frames as input, the output VFI results will have the save brightness as the DAVIS video frames, and are different from GT video frames. This is unfair for flow-based methods and flow-based module in Time Lens. If you only need **qualitative VFI results** or use it in real-world applications, you could just use low-speed video frames and the corresponding event stream between frames as input (spatiotemporal aligned frames and events), e.g. frames and events captured by DAVIS event camera (naturally aligned).

**Comment by stilcrad** [comment]
THANKS!!!!
